---
driver:
  name: vagrant

provisioner:
  require_chef_omnibus: true
  name: chef_zero
  attributes:
    stackdriver:
      api_key: '12345'
      gen_hostid: true

platforms:
  - name: centos-6.6
    run_list:
      - recipe[yum-epel::default]
  - name: centos-7.0
    run_list:
      - recipe[yum-epel::default]
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-6.0.10
  - name: debian-8.0

suites:
  - name: default
    run_list:
      - recipe[stackdriver::default]
    attributes:
      stackdriver:
        tags:
          test1: 1
          test2: 2
<% %w(apache elasticsearch memcached mongodb nginx redis).each do |name| %>
  - name: plugins_<%= name %>
    run_list:
      - recipe[stackdriver::plugins]
    attributes:
      stackdriver:
        plugins:
          <%= name %>:
            enable: true
<% end %>
