rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without guard kitchen
env:
  - CHEF_VERSION='~> 11.0'
before_script: bundle exec berks install
script:
  - bundle exec foodcritic .
  - bundle exec rubocop
  - bundle exec rspec
